### PR TITLE
Major project update

### PR DESCRIPTION
**Pull request by e2**
Hi, I'm the maintainer of Guard (https://github.com/guard/guard)  and many/most of it's plugins.

The project seems abandoned, though people do try to use this. I've updated the project to work with recent versions of Guard.

I'd recommend moving the project to the Guard organization here:

https://github.com/guard/guard-haml-coffee

(I can add you as an owner of the project). 

This makes things easier to manage if people are unavailable or step down.

@sigmike - you are the owner of the gem, you can add me in case you want me to make Guard-compatibility releases in the future:

`gem owner -a cezary.baginski@gmail.com`

### CODE REVIEW

**Comment by tommybstitch** [comment]
Can you please pull this in? I need to use this plugin and it does not work as-is.

**Comment by tommybstitch** [comment]
I have actually just pulled in your updates to the gem and am still having errors :/

**Comment by tommybstitch** [comment]
I know you've done quite a bit of work on this already, but how difficult would it be to add an 'output' option to the guardfile for haml-coffee? That would be a tremendous help.

**Comment by e2** [comment]
@tommybstitch - guard-haml-coffee already supports an `:output` option (along with an `:input` option too).

I've documented them in the `Guardfile` template.

**Comment by sigmike** [comment]
@e2 I've added you as owner of the gem and collaborator of this repository. Feel free to move it. I don't have much time to maintain it.

**Pull request merged**
